- Dockerfile
- go.mod
Updates go to version 1.22.3
Fixes #
```feature user
```
> Update to golang 1.22.3

- README.md
- imagevector/images.yaml
- imagevector/imagevector.go
- imagevector/imagevector_test.go
- pkg/constants/constants.go
- pkg/controller/lifecycle/actuator.go
- pkg/falcovalues/falcovalues.go
- pkg/secrets/certs.go
- pkg/secrets/certs_test.go
All certificates are only re-generated if they have reached a sufficient age.
Fixes #
```feature user
```
> Cert updates

- falco/falcoversions.yaml
- imagevector/images.yaml
- imagevector/imagevector_test.go
- pkg/falcovalues/falcovalues.go
- pkg/falcovalues/falcovalues_test.go
- pkg/secrets/certs.go
- pkg/secrets/tokenissuer.go
Cleanup & more tests
Fixes #
```feature user
```
> Cleanup & more tests

- charts/gardener-extension-admission-shoot-falco-service/charts/application/values.yaml
> Fix typo in values.yaml

- .ci/pipeline_definitions
- .ci/verify-falco-rules
- Makefile
- cmd/gardener-extension-shoot-falco-service/app/app.go
- falco/FalcoProfile.yaml
- hack/validate-falco-rules
- pkg/controller/lifecycle/actuator.go
- pkg/falcovalues/falcovalues.go
- pkg/falcovalues/falcovalues_test.go
- pkg/profile/profile.go
Read Falco and Falcosidekick versions from profile
Fixes #
```feature user
```
> Read Falco and Falcosidekick versions from profile

- cmd/gardener-extension-admission-shoot-falco-service/app/app.go
- pkg/admission/mutator/shoot_mutator.go
- pkg/admission/mutator/shoot_mutator_test.go
- pkg/admission/validator/shoot_validator.go
- pkg/admission/validator/shoot_validator_test.go
- pkg/profile/profile.go
> Updated validation and mutation for new Falco version mechanism

- .ci/pipeline_definitions
> next attempt

- charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
- cmd/gardener-extension-admission-shoot-falco-service/app/app.go
> Fix issues when falco extension is deployed in-cluster

- pkg/admission/mutator/shoot_mutator.go
> Fix throwing error when extension def is empty

- charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
> Put network allow label into correct place

- charts/internal/falco/templates/falco-pod-template.tpl
Adds nodename as host in events
Fixes #
```feature user
```
> Set hostname env variable for node as hostname in events

- pkg/values/falcovalues_suite_test.go
- pkg/values/falcovalues_test.go
Adds additional tests for un-covered statements
Fixes #
```feature user
```
> Adding additional falco values tests

- falco/falcosidekickversions.yaml
- imagevector/images.yaml
> Add new falcosidekick version

- .ci/hack/component_descriptor
- .ci/hack/set_dependency_version
- .ci/pipeline_definitions
> add verify on head update

- pkg/secrets/certs.go
- pkg/secrets/tokenissuer_test.go
> Added additional test for secrets module

- charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/rbac.yaml
- cmd/gardener-extension-admission-shoot-falco-service/app/app.go
- pkg/admission/validator/project.go
- pkg/admission/validator/shoot_validator.go
- pkg/admission/validator/webhook.go
- pkg/constants/constants.go
Enables selection of projects which can enable the Falco extension for alpha testing
Fixes #
```feature user
```
> Enable Falco Usage for selected Stakeholders via Project Annotation

- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
> Fix priority classes for extension controller and shoot

- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
- charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
> Fix priority class names for admission controller

- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
- charts/gardener-extension-admission-shoot-falco-service/values.yaml
- charts/gardener-extension-shoot-falco-service/values.yaml
This should fix the priority class configuration and settings for the extension, the admission controler, and falco which is deployed into shoot cluster.
Fixes #
```feature user
```
> Fix priority class configuration

- charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
- charts/internal/falco/values.yaml
- pkg/values/falcovalues.go
> Add priority class config for Falcosidekick

- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
> Fixed typo in env variable

- cmd/gardener-extension-admission-shoot-falco-service/app/app.go
> Add logging for restricted usage

- cmd/gardener-extension-admission-shoot-falco-service/app/app.go
- pkg/admission/validator/shoot_validator.go
- pkg/admission/validator/shoot_validator_test.go
> Only restrict extension usage if not previously enabled

- cmd/gardener-extension-admission-shoot-falco-service/app/app.go
> Remove unused code

- hack/api-reference/config.md
- pkg/apis/profile/v1alpha1/types.go
- pkg/profile/profile.go
Fixes [issue](https://github.com/gardener/gardener-extension-shoot-falco-service/issues/75)
```feature user
```
> Fixed expiration date nil pointer for falco related versions

- pkg/admission/validator/shoot_validator_test.go
Fixes https://github.com/gardener/gardener-extension-shoot-falco-service/issues/77
```feature user
```
> Fix and add shoot validator tests

- falco/falco-profile.yaml
- falco/falcoctlversions.yaml
- falco/falcosidekickversions.yaml
- imagevector/images.yaml
Fixes #
```ohter operator
- remove Falcosidekick version 2.28.0
- add falcoctl version 0.10.0
```
> Add new versions, remove old ones

- docs/FalcoExtension.md
> Fix configmap spec in documentation

- .ci/pipeline_definitions
Fixes #
```feature user
NONE
```
> Add verify to release steps

- .ci/pipeline_definitions
> Bumping go test image 1.23.3

- go.mod
- go.sum
- pkg/admission/validator/shoot_validator.go
- pkg/admission/validator/shoot_validator_test.go
- pkg/controller/maintenance/add.go
- pkg/controller/maintenance/reconciler.go
Fix deadlock between maintenance and admission controllers and general improvement and simplification of maintenance controller
Fixes #
```feature user
```
> [fix] Fixing deadlock between maintenance and validation controllers

- charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/rbac.yaml
- pkg/controller/maintenance/reconciler.go
Shoot maintenance needs to be able to update shoot
Fixes #
```feature user
```
> Add missing permissions for shoot update during maintenance

- pkg/controller/lifecycle/actuator.go
On extension deletion there are two resources that must be deleted. We had a case where the first resource was deleted successfully but the second was not. On all subsequent deletion attempts the first deletion failed (because it was gone) which made the whole attempt fail.
Fixes #
(popped up during integration testing)
```feature user
```
> Fix delete loop of death

- falco/falco-profile.yaml
- falco/falcoversions.yaml
- imagevector/images.yaml
- pkg/admission/mutator/shoot_mutator.go
- pkg/admission/mutator/shoot_mutator_test.go
- pkg/admission/validator/shoot_validator.go
- pkg/admission/validator/shoot_validator_test.go
- pkg/controller/maintenance/reconciler.go
- pkg/profile/profile.go
- pkg/profile/profile_test.go
- pkg/values/falcovalues.go
- pkg/values/falcovalues_test.go
This fortunately highlighted a leftover in the value generation, some information was not taken from the profile but from statically linked files.
Fixes #
```feature user
```
> Add new Falco version and remove expired versions

- charts/internal/falco/templates/falco-pod-template.tpl
- charts/internal/falco/values.yaml
Add configuration options added in later Falco versions, remove discontinued or deprecated options. 
Fixes #
```feature user
```
> Remove deprecated configuration options

- falco/falco-profile.yaml
- falco/falcoctlversions.yaml
- falco/falcosidekickversions.yaml
- imagevector/images.yaml
Maintain new versions for falcosidekick and falcoctl.
Fixes #
```feature user
```
> Add new falcosidekick and falcoctl versions

- charts/internal/falco/templates/falco-pod-template.tpl
- charts/internal/falco/templates/falcosidekick-deployment.yaml
- pkg/values/falcovalues.go
Some minor structural cleanup.
Fixes #
```feature user
```
> Minor cleanup

- cmd/gardener-extension-admission-shoot-falco-service/app/app.go
- falco/falco-profile.yaml
- falco/falcoctlversions.yaml
- falco/falcoversions.yaml
- imagevector/images.yaml
- pkg/admission/validator/shoot_validator.go
- pkg/profile/profile.go
Add new Falco and falcoctl versions as well as do some preparatory work for passing command line arguments to the validating webhook configuration.
Fixes #
```feature user
```
> Add new Falco versions (deprecate old ones)

- pkg/apis/config/types.go
- pkg/apis/config/v1alpha1/zz_generated.conversion.go
- pkg/apis/config/zz_generated.deepcopy.go
- pkg/cmd/config.go
> mitigate gardener api change

- .github/dependabot.yaml
> Add `ok-to-test` label for dependabot

- falco/falco-profile.yaml
- imagevector/images.yaml
> fix falcoctlversion (again)

- pkg/controller/lifecycle/actuator.go
- pkg/secrets/tokenissuer.go
- pkg/secrets/tokenissuer_test.go
- pkg/values/falcovalues_test.go
Tt was set to 2 days instead of the configured value.
Fixes #
```feature user
```
> Fix token lifetime

- .ci/pipeline_definitions
> Bump golang-1.23.6 ci image

- Dockerfile
- go.mod
> Bump golang-1.23.6

- falco/falco-profile.yaml
- falco/falcosidekickversions.yaml
- imagevector/images.yaml
> Added new falcosidekick version 2.31.1

- .ci/pipeline_definitions
> Publish falco profile as oci artefact

- .ci/pipeline_definitions
fix strange quoting issue 
Fixes #
```feature user
```
> fix build issue

- go.mod
- go.sum
- pkg/controller/maintenance/add.go
- pkg/controller/maintenance/reconciler.go
Fixes #https://github.com/gardener/gardener-extension-shoot-falco-service/issues/143
```feature user
```
> Unified logging for maintenance

- .ci/pipeline_definitions
> attach falco rules to com component

- .ci/pipeline_definitions
> Fix pipeline

- .ci/pipeline_definitions
> fix pipeline 6

- .ci/pipeline_definitions
> fix pipeline 7

- falco/rules/3.2.0/falco_rules.yaml
> Add falco rule exception for new runc version

- .ci/component_descriptor
> fix: Use relative path working on Concourse

- .ci/component_descriptor
> fix: Properly write ocm to expected output

- .ci/hack/component_descriptor
> Make go-mod-tidy happy again

- Makefile
- hack/validate-imagevector.py
A wrong image reference broke our release process downstream. 
Fixes #
```feature user
```
> validate that all additional images do exist

- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
- charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
- charts/internal/falco/templates/falcosidekick-deployment.yaml
- charts/internal/falco/templates/falcosidekick-secrets.yaml
- charts/internal/falco/templates/falcosidekick-service.yaml
- charts/internal/falco/values.yaml
- pkg/values/falcovalues.go
- pkg/values/falcovalues_test.go
This PR resolves compliancy issues:
- secrets must not be passed as environment variables
- some diki issues
Note: writing to vali does not work in the development setup, however the original implementation also does not work in the development setup. I am quite sure that the configuration is identical.
Fixes #
```feature user
```
> Remove env config

- Makefile
- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
- charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
- pkg/admission/validator/shoot_validator.go
- pkg/constants/constants.go
> Finalize configuration options for restricted usage

- .ci/pipeline_definitions
> Update verify image golang 1.24.1

- go.mod
- go.sum
> Update x/net 0.36.0

- crds/crd-falco-profile.yaml
Fixes #https://github.com/gardener/gardener-extension-shoot-falco-service/issues/163
```feature user
```
> Remove last reference of architecture for images

- falco/falco-profile.yaml
- falco/falcoversions.yaml
Mark Falco 0.40.0 as supported.
Fixes #
```feature user
```
> mark Falco 0.40.0 as supported

- .test-defs/TestFalco.yaml
- Makefile
- test/integration/.gitignore
- test/integration/conftest.py
- test/integration/falco-integration.sh
- test/integration/falcotest/falcolib.py
- test/integration/requirements.txt
- test/integration/test_falco.py
> Add integration tests

- hack/api-reference/service.md
- pkg/values/falcovalues.go
> Fix for broken vali logging

- charts/internal/falco/values.yaml
- hack/api-reference/service.md
Enable faster rolling of Falco pods in clusters
Fixes #
```feature user
```
> Increase maxUnavailable for falco ds updates

- charts/internal/falco/values.yaml
> Change maxUnavailable to 20%

- hack/api-reference/service.md
- hack/test.sh
- pkg/secrets/certs.go
- pkg/values/falcovalues_test.go
Speeds up unit test running time
Fixes #
```feature user
```
> Allow shorter key length in unit tests

- hack/api-reference/service.md
- pkg/admission/validator/shoot_validator.go
- pkg/admission/validator/shoot_validator_test.go
> Fix central logging validation

- falco/falco-profile.yaml
- falco/falcoversions.yaml
- hack/api-reference/service.md
> Deprecate Falco version 0.39.2

- pkg/admission/validator/shoot_validator.go
> Improve error message of admission controller

- Makefile
- falco/falco-profile.yaml
- falco/falcoctlversions.yaml
- hack/generate-falco-profile
- imagevector/images.yaml
We have removed Falcoctl support from the extension. We also don't need it anymore in the profile.
Fixes #
```feature user
```
> Remove Falcoctl entries from profile

- charts/internal/falco/values.yaml
Enable Falco metrics for Prometheus.
Fixes #
```feature user
```
> Enable Falco metrics endpoint

- falco/falco-profile.yaml
- falco/falcosidekickversions.yaml
- falco/falcoversions.yaml
- imagevector/images.yaml
Remove obsolete and/or expired versions. Set expiration date for Falco 0.39.2
Fixes #
```feature user
Expire Falco 0.39.2 on July 28th 2025
```
> Remove obsolete falco and falcosidekick versions

- test/integration/.gitignore
> Dont commit intgeration test log file

- charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/rbac.yaml
Addresses https://github.com/gardener/gardener-extension-shoot-falco-service/issues/261
```feature user
```
> Remove unused project access from admission controller

- hack/api-reference/service.md
> make generate

- charts/internal/falco/values.yaml
> Disable noisy metrics rule

- charts/internal/falco/templates/falcosidekick-deployment.yaml
> Do not automount default service account token for falcosidekick

- charts/gardener-extension-shoot-falco-service/templates/rbac.yaml
> Limit extension access via rbac to this extension

- charts/internal/falco/templates/0helpers.tpl
- charts/internal/falco/values.yaml
> Use Gardener image reference for heartbeat container

- charts/internal/falco/values.yaml
> Remove CPU limits for Falco pod

- charts/internal/falco/values.yaml
> Increase memory requests and limits to deal with leaking Falco

- charts/internal/falco/values.yaml
- pkg/values/falcovalues.go
> Respect gardener critical component taint

- charts/internal/falco/values.yaml
> Decrease memory requests and limits

- charts/internal/falco/templates/0helpers.tpl
Fixed container mounts for extra fields for Falco Version 0.40.0
Fixes #
```feature user
```
> Fix volume mounts for container engine in 0.40.0
