Makefile
charts/internal/falco/templates/falco-pod-template.tpl
charts/internal/falco/values.yaml
cmd/gardener-extension-shoot-falco-service/app/app.go
falco/falcoversions.yaml
pkg/falcovalues/falcovalues.go

- lowercase text messages
- allow to start extension and webhook server on same host
- work around a missing docker desktop feature on linux (host.docker.internal hostname)
- introduce falco version 0.38
- allow configuration to work with Falco 0.37.x and 0.38.x
- fixed bug putting certificates into secrets (double base64)
-
Fixes #
```feature user
```

General cleanup

---

charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
charts/gardener-extension-admission-shoot-falco-service/values.yaml

**How to categorize this PR?**
/area robustness
/kind enhancement
This PR enhances the admission chart by the option to set a `priorityClassName`.
Part of https://github.com/gardener/gardener/issues/9936.
```other operator
A `priorityClassName` can now be set for the admission deployment via the `gardener-extension-admission-shoot-falco-service` Helm chart.
```

[admission] Add `priorityClassName`

---

charts/internal/falco/templates/falco-pod-template.tpl
pkg/falcovalues/falcovalues.go
pkg/falcovalues/falcovalues_test.go

Fix propagation of priority class name. Falco daemonsets did not have a priority class name which causes some pods not to be launched on seeds.
Fixes #
```feature user
```

Fix propagation of priority class name

---

pkg/falcovalues/falcovalues.go
pkg/falcovalues/falcovalues_test.go

Add support for custom webhooks as described in
https://github.com/gardener/gardener/blob/a0f959ee152e13a22db1b0d9f6f146bc16c8b7ed/docs/proposals/27-falco-extension.md#proposal
Fixes #
```feature user
Add support for custom webhook configuration in FalcoServiceConfig.
```

Custom webhook support

---

charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
charts/gardener-extension-admission-shoot-falco-service/values.yaml
pkg/admission/validator/shoot_validator.go

This PR added a way to configure the preview feature. It is disabled by default but can be enabled by setting the environment variable `RESTRICTED_USAGE` to `true`. 
If set, projects must have the annotation `falco.gardener.cloud/enabled=true` for adding falco to shoot clusters.
Fixes #
```feature user
```

Add preview flag to admission controller

---

charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml

Without quotes the deployment fails with the following error: ` json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`
Fixes #
```feature user
```

Avoid deployment failure

---

charts/internal/falco/values.yaml

This functionality was removed in Falco 0.38 and now throws a warning during startup of Falco 0.39.1. This avoids the following message during Falco startup:
```
Fri Oct 18 05:04:34 2024:    /etc/falco/falco.yaml | schema validation: failed for <root>: Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints: 'metadata_download'.
```
Fixes #
```feature user
```

Removing the metadata_download configuration

---

falco/falco-profile.yaml
falco/falcoversions.yaml
imagevector/images.yaml

Support now Falco version 0.39.1 and deprecate all older versions early.
Fixes #
```feature user
Support new Falco version 039.1.
```

Support new falco version with new ruleset

---

charts/internal/falco/values.yaml

It appears that we cannot easily scrape `/metrics` endpoints in shoots via https. This PR makes the `/metrics` endpoint of Falcosidekick available via http.
Fixes #
```feature user
```

Make /metrics endpoint available via http

---

.ci/pipeline_definitions

Anchor 'golang-test' missing in pipleline_definitions
Fixes #
```feature user
```

Fix pipleline

---

falco/falco-profile.yaml
falco/falcoversions.yaml

Falco versions < 0.39.2 do not work with Garden Linux 1592.3.
Fixes #
```feature user
```

Set Falo version 0.39.2 as supported

---

charts/internal/falco/templates/falco-pod-template.tpl
charts/internal/falco/templates/falcosidekick-deployment.yaml
pkg/values/falcovalues.go

Remove pod labels that are not relevant for all Falco deployments.
Fixes #
```feature user
```

Remove pod labels

---

charts/internal/falco/templates/falcosidekick-networkpolicy.yaml
charts/internal/falco/values.yaml

The network policy is needed / was needed in case network policies for the falco and falcosidekick pods are not fully managed by the gardener resource manager. We have a case now where the deployment of that network policy that was problematic and need a way to disable it.
Fixes #
```feature user
```

Add option to deploy falco-falcosidekick networkpolicy

---

pkg/admission/mutator/shoot_mutator.go
pkg/admission/mutator/shoot_mutator_test.go

The extension panicked when output.logFalcoEvents was unset. Added test and fix.
Fixes #
```feature user
```

Fix glitch in shoot mutator

---

go.mod
pkg/constants/constants.go
pkg/values/falcovalues.go
pkg/values/falcovalues_test.go

**How to categorize this PR?**:
/kind enhancement
Add compression capabilities as described in #146 
Fixes #
```feature user
Falco custom rules files may now be provided in compressed `gzip` format. Compressed rules files (`.gz` file extension) can be readily added to a Configmap and referenced in the usual way.
```

Add compression capability for Falco custom rules

---

Makefile
hack/validate-falco-rules
hack/validate-imagevector.py
pkg/constants/constants.go
pkg/values/falcovalues.go
pkg/values/falcovalues_test.go

Fix ordering of custom rules. The implementation did not match the documentation and the procedure stated in the documentation could not have been implemented, see release notes below. The number of possible rule files per configmap is now limited to 10.
Also added validation for images in imagevector.
Fixes #
```feature user
Fixed the ordering for custom rules. Custom rules are now deployed in the following order: (1) in the oder they are referenced in the customRules key and (2) rule files in configmaps are sorted in alphanumerical order.
```

Improve custom rule handling

---

falco/rules/3.2.0/falco_rules.yaml

Avoid lots of false positives due to Dynatrace.
Fixes #
```feature user
Add Falco exception to avoid false positives when Dynatrace is deployed.
```

Add Dynatrace exception

---

charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/poddisruptionbudget.yaml
charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/service.yaml
hack/api-reference/config.json
hack/api-reference/config.md
hack/api-reference/service.json

- Adapt PDBs to use unhealthyPodEvictionPolicy: AlwaysAllow unconditionally
- Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.26.
- Adapt service.kubernetes.io/topology-mode annotation
Part of https://github.com/gardener/gardener/issues/10339
N/A
```feature user
`extension-shoot-falco-service` no longer supports Shoots with Кubernetes version <= 1.26.
```

Drop support for Shoots with Kubernetes version <= 1.26

---

falco/rules/3.2.0/falco_rules.yaml

The upstream exception changed upstream from the exception that we adopted. This should avoid false positive events from runc.
Fixes #
```feature user
```

Adopt upstream exception for new runc version

---

charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/service.yaml

**How to categorize this PR?**
/area networking
/area high-availability
See more details in https://github.com/gardener/gardener/issues/10421 and https://github.com/gardener/gardener/pull/11178.
Part of https://github.com/gardener/gardener/issues/10421
N/A
```other operator
The [`ServiceTrafficDistribution`](https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-distribution) feature is being used on to make Services topology-aware when the runtime Kubernetes version is 1.31+.
```

Use ServiceTrafficDistribution to make Services topology-aware when runtime Kubernetes >= 1.31

---

pkg/admission/mutator/shoot_mutator.go
pkg/admission/mutator/shoot_mutator_test.go

Fixes a nil pointer dereference error for empty extension configs in the shoot spec
```feature user
```

Fix empty extension spec

---

charts/gardener-extension-shoot-falco-service/templates/rbac.yaml

**How to categorize this PR?**
/area quality
/kind regression
Similar to https://github.com/gardener/gardener-extension-os-gardenlinux/pull/256
N/A
N/A
```other operator
NONE
```

Allow `patch` of the `gardener-extension-heartbeat` lease

---

Makefile
example/.gitignore
example/doc.go
example/extension.yaml
example/extension/base/extension.yaml
example/extension/base/kustomization.yaml
example/extension/extension.yaml
example/extension/kustomization.yaml
hack/api-reference/service.md

**How to categorize this PR?**
/area ops-productivity
/kind enhancement
This PR adds the generation for an `Extension` example manifest.
```other operator
An example `Extension` manifest for extension registration has been added. It can be found at [`example/extension.yaml`](https://github.com/gardener/gardener-extension-shoot-falco-service/blob/master/example/extension.yaml)
```

Add generation for `Extension` example

---

charts/gardener-extension-shoot-falco-service/templates/rbac.yaml

Extension SA needs patch permission for managedresources when migrating control-plane
Fixes #
```feature user
```

Give extension SA patch permission for managedresources
